name = "Invisible War"
uid = "16678e1e-7fc9-11e5-8bcf-dayofsex0010"
version = 1.0
copyright = "© 2016 Sean Wheeldon"
description = "Everything has cloak. Did you remember your scouts?"
author = "Sean Wheeldon"
icon = "/mods/Requestathon/InvisibleWar/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
before = {  }
after = {  }
