name = "Harbinger Type-C"
uid = "16678e1e-7fc9-11e5-8bcf-harbinger010"
version = 1.0
copyright = "© 2016 Sean Wheeldon"
description = "Now USB compatible."
author = "Sean Wheeldon"
icon = "/mods/Requestathon/HarbingerMKIII/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
before = {  }
after = {  }
